/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./events/**/*.html",
    "./news/**/*.html",
    "./programs/**/*.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    /* Six-size type scale: xs 12 · sm 14 · base/lg 16 · xl 20 · 2xl/3xl 24 · 4xl+ 36 */
    fontSize: {
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1rem", { lineHeight: "1.5rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.5rem", { lineHeight: "2rem" }],
      "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "5xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "6xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "7xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "8xl": ["2.25rem", { lineHeight: "2.5rem" }],
      "9xl": ["2.25rem", { lineHeight: "2.5rem" }],
    },
    extend: {
      colors: {
        primary: "#142C8D",
        "primary-light": "#1E40AF",
        "primary-dark": "#0F2461",
        "primary-container": "#E22830",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#FFFFFF",
        secondary: "#1E40AF",
        "secondary-container": "#DBEAFE",
        "on-secondary": "#FFFFFF",
        accent: "#B45309",
        "accent-light": "#D97706",
        cta: "#E22830",
        surface: "#F8FAFC",
        "surface-bright": "#FFFFFF",
        "surface-container": "#F1F5F9",
        "surface-container-low": "#F8FAFC",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "surface-variant": "#E2E8F0",
        "surface-dim": "#F1F5F9",
        "on-surface": "#0F172A",
        "on-surface-variant": "#475569",
        "on-background": "#0F172A",
        background: "#F8FAFC",
        outline: "#94A3B8",
        "outline-variant": "#E2E8F0",
        "inverse-surface": "#0F172A",
        "inverse-on-surface": "#F8FAFC",
        "inverse-primary": "#93C5FD",
        error: "#DC2626",
        "error-container": "#FEE2E2",
        "on-error": "#FFFFFF",
        "on-error-container": "#991B1B",
        tertiary: "#0E7490",
        "tertiary-container": "#CFFAFE",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#164E63",
        "primary-fixed": "#DBEAFE",
        "primary-fixed-dim": "#93C5FD",
        "on-primary-fixed": "#0F172A",
        "on-primary-fixed-variant": "#1E40AF",
        "secondary-fixed": "#DBEAFE",
        "secondary-fixed-dim": "#93C5FD",
        "on-secondary-fixed": "#0F172A",
        "on-secondary-fixed-variant": "#1E40AF",
        "tertiary-fixed": "#CFFAFE",
        "tertiary-fixed-dim": "#67E8F9",
        "on-tertiary-fixed": "#0F172A",
        "on-tertiary-fixed-variant": "#0E7490",
        "surface-tint": "#142C8D",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Lexend", "system-ui", "sans-serif"],
        body: ["Source Sans 3", "system-ui", "sans-serif"],
        label: ["Lexend", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)",
        "card-hover":
          "0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.04)",
        nav: "0 4px 24px -4px rgba(15, 23, 42, 0.12)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
